[package]
name = "tiny-wasm-runtime"
version = "0.1.1"
edition = "2021"
autotests = false
description = "A minimal, single-threaded async runtime for WASI Preview 3 components"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
repository = "https://github.com/StaticallyTypedAnxiety/tiny-async-runtime"
readme = "README.md"
keywords = ["wasi", "wasm", "async", "component-model"]
categories = ["wasm", "asynchronous", "network-programming"]

[package.metadata.docs.rs]
targets = ["wasm32-wasip2"]
default-target = "wasm32-wasip2"

[dependencies]
futures = "0.3.30"
wit-bindgen = { version = "0.60.0", features = ["async", "async-spawn", "bitflags"] }
pin-project-lite = "0.2.16"
tiny-wasm-runtime-macros = { version = "0.1.0", path = "tiny-wasm-runtime-macros" }

[package.metadata.component]
package = "component:wasm-runtime"

[package.metadata.component.target.dependencies]
"wasi:clocks" = {path = "wit/deps/clocks"}
"wasi:sockets" = {path = "wit/deps/sockets"}
"wasi:cli" = {path = "wit/deps/cli"}

[[example]]
name = "basic_usage"
crate-type = ["cdylib"]

[[example]]
name = "macro_main"
crate-type = ["cdylib"]

[[example]]
name = "test-engine"
path = "tests/engine.rs"
crate-type = ["cdylib"]

[[example]]
name = "test-timers"
path = "tests/timers.rs"
crate-type = ["cdylib"]

[[example]]
name = "test-macro-main"
path = "tests/macro_main.rs"
crate-type = ["cdylib"]

[[example]]
name = "test-usage-example"
path = "tests/usage_example.rs"
crate-type = ["cdylib"]

[[example]]
name = "test-network"
path = "tests/network.rs"
crate-type = ["cdylib"]

[[example]]
name = "experiment-directory-server"
path = "examples/chat/directory_server.rs"
crate-type = ["cdylib"]

[[example]]
name = "experiment-chat-peer"
path = "examples/chat/chat_peer.rs"
crate-type = ["cdylib"]

[[example]]
name = "experiment-chat-demo"
path = "examples/chat/chat_demo.rs"
crate-type = ["cdylib"]

[[bin]]
name = "high-frequency-benchmark"
path = "benchmarks/high_frequency_benchmark.rs"
