package component:wasm-runtime;

/// An example world for the component to target.
world wasm-runtime {
    import wasi:clocks/monotonic-clock@0.3.0;
    import wasi:sockets/types@0.3.0;
}

world wasm-runtime-command {
    include wasm-runtime;
    export wasi:cli/run@0.3.0;
}
